version: '3.7'

services:
  php:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./app/public:/var/www/html/public
      - ./apache-config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-config/app.conf:/etc/apache2/sites-available/app.conf
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: app
      MYSQL_root: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password!
    ports:
      - "8081:80"
    depends_on:
      - mysql
